package com.qiongsong.ficus.dal;

import java.util.regex.Pattern;

/**
 * Unit test for simple App.
 */
public class AppTest {

  public static void main(String[] args) {
    String sql = "SELECT     "
        + "EOOR.SITE_CODE,    "
        + "EOOR.SITE_NAME,   "
        + "EOOR.EOOR_IS_COLLECTION_AMOUNT,    "
        + "EOOR.EOOR_EXCPEPT_TIME,  "
        + "/*预计送达时间*/ EOOR.EOOR_RESERVATION_STATUS,     "
        + "/*预约状态*/ EOOR.EOOR_SPD_LOGISTIC_NO,   "
        + "/*物流订单SPD物流号*/ EOOR.EOOR_RESERVATION_TIME, "
        + "/*预约时间*/ EOOR.EOOR_IS_TAKE_DELIVERY_HOLIDAY,    "
        + "/*节假日是否送货*/ EOOR.EOOR_EXPRESS_NO,"
        + "/*快递单号*/ EOOR.EOOR_ID, "
        + "EOOR.CREATOR,     "
        + "EOOR.CREATE_TIME, "
        + "EOOR.MODIFIER,     "
        + "EOOR.MODIFY_TIME, "
        + "EOOR.REC_VER,     "
        + "EOOR.REC_STATUS,  "
        + "EOOR.ORG_ID,       "
        + "EOOR.EOOR_ORDER_NO,      "
        + "EOOR.EOOR_LOGISTIC_NO,    "
        + "EOOR.EOOR_ORDER_TYPE_CODE,"
        + "EOOR.EOOR_ORDER_TYPE_NAME,"
        + "EOOR.EOOR_PRIORITY_CODE,  "
        + "EOOR.EOOR_PRIORITY_NAME, "
        + "EOOR.EOOR_TRANS_TYPE_CODE,"
        + "EOOR.EOOR_TRANS_TYPE_NAME,"
        + "EOOR.EOOR_STATUS_CODE,   "
        + "EOOR.EOOR_STATUS_NAME,   "
        + "EOOR.EOOR_CUSTOMER_CODE,"
        + "EOOR.EOOR_CUSTOMER_NAME,"
        + "EOOR.EOOR_CUSTOMER_CONTACT_CODE, "
        + "EOOR.EOOR_CUSTOMER_CONTACT_NAME, "
        + "EOOR.EOOR_CUSTOMER_CONTACT_PHONE,"
        + "EOOR.EOOR_ORDER_TIME,     "
        + "EOOR.EOOR_DIVIDE_CODE,    "
        + "EOOR.EOOR_DIVIDE_NAME,    "
        + "EOOR.EOOR_REQUIRE_SHIPPER_TIME_FM, "
        + "EOOR.EOOR_REQUIRE_SHIPPER_TIME_TO, "
        + "EOOR.EOOR_REQUIRE_CONSIGNEE_TIME_FM,       "
        + "EOOR.EOOR_REQUIRE_CONSIGNEE_TIME_TO,       "
        + "EOOR.EOOR_ORDER_DEPARTMENT_CODE, "
        + "EOOR.EOOR_ORDER_DEPARTMENT_NAME, "
        + "EOOR.EOOR_OPERATE_DEPARTMENT_CODE,        "
        + "EOOR.EOOR_OPERATE_DEPARTMENT_NAME,       "
        + "EOOR.EOOR_SHIPPER_CODE,  "
        + "EOOR.EOOR_SHIPPER_NAME,  "
        + "EOOR.EOOR_SHIPPER_CONTACT_CODE,   "
        + "EOOR.EOOR_SHIPPER_CONTACT_NAME,   "
        + "EOOR.EOOR_SHIPPER_CONTACT_PHONE,  "
        + "EOOR.EOOR_SHIPPER_LOCATION_CODE,   "
        + "EOOR.EOOR_SHIPPER_LOCATION_NAME,   "
        + "EOOR.EOOR_SHIPPER_REGION_CODE,     "
        + "EOOR.EOOR_SHIPPER_REGION_NAME,     "
        + "EOOR.EOOR_SHIPPER_CITY_CODE,        "
        + "EOOR.EOOR_SHIPPER_CITY_NAME,        "
        + "EOOR.EOOR_SHIPPER_DISTRICT_CODE,    "
        + "EOOR.EOOR_SHIPPER_DISTRICT_NAME,   "
        + "EOOR.EOOR_CONSIGNEE_CODE, "
        + "EOOR.EOOR_CONSIGNEE_NAME, "
        + "EOOR.EOOR_CONSIGNEE_CONTACT_CODE,"
        + "EOOR.EOOR_CONSIGNEE_CONTACT_NAME,"
        + "EOOR.EOOR_CONSIGNEE_CONTACT_PHONE,        "
        + "EOOR.EOOR_CONSIGNEE_LOCATION_CODE,"
        + "EOOR.EOOR_CONSIGNEE_LOCATION_NAME,"
        + "EOOR.EOOR_CONSIGNEE_REGION_CODE,  "
        + "EOOR.EOOR_CONSIGNEE_REGION_NAME,  "
        + "EOOR.EOOR_CONSIGNEE_CITY_CODE,     "
        + "EOOR.EOOR_CONSIGNEE_CITY_NAME,     "
        + "EOOR.EOOR_CONSIGNEE_DISTRICT_CODE, "
        + "EOOR.EOOR_CONSIGNEE_DISTRICT_NAME, "
        + "EOOR.EOOR_COLLECTION_AMOUNT,       "
        + "EOOR.EOOR_PO_NO, "
        + "EOOR.EOOR_SO_NO, "
        + "EOOR.EOOR_SOURCE_CODE,   "
        + "EOOR.EOOR_SOURCE_NAME,  "
        + "EOOR.EOOR_DO_NO, "
        + "EOOR.EOOR_BARCODE,        "
        + "EOOR.EOOR_PACKAGE_QUANTITY,        "
        + "EOOR.EOOR_QUANTITY,       "
        + "EOOR.EOOR_GROSS_WEIGHT,  "
        + "EOOR.EOOR_NET_WEIGHT,     "
        + "EOOR.EOOR_VOLUME,"
        + "EOOR.EOOR_WEIGHT_VOLUME, "
        + "EOOR.EOOR_REQUIREMENT,   "
        + "EOOR.EOOR_REMARK,"
        + "EOOR.EOOR_MEGER_FLAG,    "
        + "EOOR.EOOR_LINK_ORDER_NO, "
        + "EOOR.EOOR_EXPIRATION_TIME,"
        + "EOOR.EOOR_RESERVATION,   "
        + "EOOR.EOOR_SALESMAN_CODE,"
        + "EOOR.EOOR_SALESMAN_NAME,"
        + "EOOR.EOOR_SPLIT_FLAG,      "
        + "EOOR.EOOR_EMERGENT_FLAG,"
        + "EOOR.EOOR_EVENT_OBJECT_CODE,       "
        + "EOOR.EOOR_EVENT_OBJECT_NAME,       "
        + "EOOR.EOOR_PAYMENT_TYPE_CODE,      "
        + "EOOR.EOOR_PAYMENT_TYPE_NAME,      "
        + "EOOR.EOOR_WAREHOUSER_CODE,        "
        + "EOOR.EOOR_WAREHOUSER_NAME,        "
        + "EOOR.EOOR_STATION_CODE,  "
        + "EOOR.EOOR_STATION_NAME,  "
        + "EOOR.EOOR_EDITABLE,        "
        + "EOOR.EOOR_AMOUNT,"
        + "EOOR.EOOR_SELLING_CUSTOMER_CODE,  "
        + "EOOR.EOOR_SELLING_CUSTOMER_NAME,  "
        + "EOOR.EOOR_EVENT_STATUS_CODE,       "
        + "ESUS.ESUS_LOGIN_NAME,     "
        + "ESUS.ESUS_USER_NAME_CN,  "
        + "ESUS.ESUS_USER_NAME_EN,  "
        + "EOOR.EOOR_MAIN_ORDER_NO ,"
        + "EOOR.EOOR_SPD_NO ,        "
        + "EOOR.EOOR_OPS_NO ,        "
        + "EOOR.EOOR_TRANS_NO ,      "
        + "EOOR.EOOR_SECOND_TRANS_NO ,        "
        + "EOOR.EOOR_CUSTOMER_ORDER_TIME ,   "
        + "EOOR.EOOR_SPD_ORDER_TIME , "
        + "EOOR.EOOR_REQUIRE_SHIPPER_TIME ,   "
        + "EOOR.EOOR_REQUIRE_CONSIGNEE_TIME , "
        + "EOOR.EOOR_CARRIER_CODE , "
        + "EOOR.EOOR_CARRIER_NAME , "
        + "EOOR.EOOR_INTERCEP_STATUS_CODE ,   "
        + "EOOR.EOOR_TRANSIT_HUB_CODE ,        "
        + "EOOR.EOOR_TRANSIT_HUB_NAME ,       "
        + "EOOR.EOOR_SUPPLIER_CODE ,"
        + "EOOR.EOOR_SUPPLIER_NAME ,"
        + "EOOR.EOOR_IS_POSITIVE ,    "
        + "EOOR.EOOR_SHIPPER_PROVINCE_CODE , "
        + "EOOR.EOOR_SHIPPER_PROVINCE_NAME , "
        + "EOOR.EOOR_SHIPPER_ADDRESS ,        "
        + "EOOR.EOOR_CONSIGNEE_CONTACT_TEL , "
        + "EOOR.EOOR_CONSIGNEE_PROVINCE_CODE ,        "
        + "EOOR.EOOR_CONSIGNEE_PROVINCE_NAME ,       "
        + "EOOR.EOOR_CONSIGNEE_STREET_CODE , "
        + "EOOR.EOOR_CONSIGNEE_STREET_NAME , "
        + "EOOR.EOOR_CONSIGNEE_ADDRESS ,      "
        + "EOOR.EOOR_BUYER_REMARK ,"
        + "EOOR.EOOR_SELLER_REMARK ,"
        + "EOOR.EOOR_IS_FREIGHT ,     "
        + "EOOR.EOOR_PRETREATMENT_TOTAL_FEE ,"
        + "EOOR.EOOR_CARGO_VALUE ,  "
        + "EOOR.EOOR_IS_EQUAL_PAYMENT ,       "
        + "EOOR.EOOR_IS_WAYBILL ,     "
        + "EOOR.EOOR_INVOICE_REQUEST ,"
        + "EOOR.EOOR_IS_UPSTAIR ,     "
        + "EOOR.EOOR_DELIERY_SETUP_TYPE ,     "
        + "EOOR.EOOR_TRANS_TIME ,    "
        + "EOOR.EOOR_CUSTOM_SERVICE_CODE ,   "
        + "EOOR.EOOR_CUSTOM_SERVICE_NAME ,   "
        + "EOOR.EOOR_CUSTOM_SERVICE_REMARK ,"
        + "EOOR.EOOR_IS_EMERGENCY , "
        + "EOOR.EOOR_REJECT_REASON ,"
        + "EOOR.EOOR_REJECT_DATE ,   "
        + "EOOR.EOOR_IS_SHIPPER_APPOINT ,      "
        + "EOOR.EOOR_SHIPPER_APPOINT_DATE ,   "
        + "EOOR.EOOR_IS_CONSIGNEE_APPOINT ,   "
        + "EOOR.EOOR_CONSIGNEE_APPOINT_DATE ,"
        + "EOOR.EOOR_COLLECTION_DELIVERY ,     "
        + "EOOR_PAY_STATUS ,"
        + "EOOR_IS_INVOICE ,  "
        + "EOOR_INVOICE_TYPE ,        "
        + "EOOR_INVOICE_TITLE ,        "
        + "EOOR_DELIVERY_TYPE ,      "
        + "EOOR_DELIVERY_DATE_TYPE ,"
        + "EOOR_IS_POD ,      "
        + "EOOR_BUSINESS_RESULT ,    "
        + "EOOR_ORIGINAL_OPS_NO ,    "
        + "EOOR_ORIGINAL_ORDER_NO ,  "
        + "EOOR_OUTBOUND_TIME ,      "
        + "EOOR_HUB_RECEIVE_TIME ,   "
        + "EOOR_PAY_TIME ,   "
        + "EOOR_FINANCE_APPROVAL_TIME ,        "
        + "EOOR_SPD_WORK_NO ,        "
        + "EOOR_CARGO_PAY_TYPE ,    "
        + "EOOR_INSTALL_DATE ,        "
        + "EOOR_IS_B2C ,      "
        + "EOOR_PACKAGE_REQUIRE ,   "
        + "EOOR_CONSIGNEE_CONTACT_ID_CARD ,   "
        + "EOOR_LOGISTICS_SEND_DATE ,"
        + "EOOR_LOGISTICS_RECEIVE_DATE ,       "
        + "EOOR_ADVISE_CARRIER_CODE , "
        + "EOOR_ADVISE_CARRIER_NAME , "
        + "EOOR_SHIPPER_STREET_CODE , "
        + "EOOR_SHIPPER_STREET_NAME , "
        + "EOOR.EOOR_FACT_CARRIER_CODE ,      "
        + "EOOR.EOOR_FACT_CARRIER_NAME ,      "
        + "EOOR.EOOR_STORE_NAME ,   "
        + "EOOR.EOOR_PRINT_COUNT ,   "
        + "--打印次数 EOOR.EOOR_IS_PRINT ,     "
        + "--是否打印 EOOR.EOOR_WAVE_CODE,  "
        + "--波次号 EOOR.EOOR_SALE_CODE,      "
        + "--发票关联号 EOOR.EOOR_SHORT_CODE,        "
        + "--短单号 EOOR.EOOR_ORIGINAL_QTY,   "
        + "--原件数 EOOR.EOOR_IS_ALL_INTERCEPT,        "
        + "--是否全冲 EOOR.EOOR_POINT_NAME,  "
        + "--拦截点 EOOR.EOOR_POINT_CODE,     "
        + "--拦截点 EOOR.EOOR_IS_TRANSPORT,  "
        + "--是否运输 EOOR.EOOR_IS_STORCK_OUT,        "
        + "--是否出库 EOOR.EOOR_IS_STORCK_IN, "
        + "--是否入库 EOOR.EOOR_IS_SEND_SPD, "
        + "--是否入库 EOOR.EOOR_HAS_LINE,     "
        + "--是否班车 EOOR.EOOR_IS_JLP,        "
        + "--是否班车 EOOR.EOOR_CUSTOMER_APPROVAL_TIME,       "
        + "--客审时间 EOOR.EOOR_BUSINESS_APPROVAL_TIME,        "
        + "--商审时间 EOOR.EOOR_FACT_OUTBOUND_TIME, "
        + "--实际出库时间 EOOR.EOOR_PICKING_GOODS,  "
        + "--拣货时间 EOOR.EOOR_STORCK_IN,    "
        + "--入库时间 EOOR.EOOR_TRANS_CHANGE,        "
        + "--运输转换标识 EOOR.EOOR_EXCEPTION_STATUS, "
        + "(CASE   "
        + "    WHEN EOOR.EOOR_FACT_OUTBOUND_TIME IS NULL THEN 'N'       "
        + "    ELSE 'Y'"
        + "END) OUTBOUND_STATUS,    "
        + "(CASE   "
        + "    WHEN EOOR_EMERGENT_FLAG='Y' THEN 'Y'    "
        + "    ELSE 'N'"
        + "END) as EMERGENT_MARK,   "
        + "EOOR.EOOR_CUSTOMER_TYPE,"
        + "/*客户单据类型*/ EOOR.EOOR_CONFIRM_RETURN_TIME,    "
        + "(CASE   "
        + "    WHEN EOOR.EOOR_IS_JLP='N'"
        + "    and EOOR_IS_TRANSPORT='Y' THEN 'Y'"
        + "    ELSE 'N'"
        + "END) EOOR_IS_JLP_REV,      "
        + "/*是否SPD2.0运输*/ EOOR.EOOR_EXECUTE_STATUS,       "
        + "EOOR.EOOR_FA_FLAG,        "
        + "EOOR.EOOR_INVENTORY_WH_CODE,       "
        + "EOOR.EOOR_INVENTORY_WH_NAME,       "
        + "EOOR.ESST_CODE,   "
        + "EOOR.ESST_NAME,   "
        + "EOOR.EOOR_PROPERTY_OWNER_CODE,   "
        + "EOOR.EOOR_PROPERTY_OWNER, "
        + "EOOR.EOOR_PLATFORM_CODE,"
        + "EOOR.EOOR_PROMTION_TYPE, "
        + "EOOR.EOOR_LINE,    "
        + "EOOR.EOOR_MILEAGE,        "
        + "EOOR.EOOR_CHARGE_AGAINST_REASON,  "
        + "EOOR.EOOR_BUYER_ORDER_TIME,        "
        + "EOOR.EOOR_SHIPPER_BOOKING_DATE_FROM,      "
        + "EOOR.EOOR_SHIPPER_BOOKING_DATE_TO,"
        + "EOOR.EOOR_SHIPPER_CONTACT_TEL,     "
        + "EOOR.EOOR_RETURN_GOODS_REASON,   "
        + "EOOR.EOOR_PARSE_AREA,    "
        + "EOOR.EOOR_PARSE_NETPOINT,"
        + "EOOR.EOOR_CONSIGNEE_WAREHOUSER_CODE,     "
        + "EOOR.EOOR_CONSIGNEE_WAREHOUSER_NAME,     "
        + "EOOR.COMPANY_CODE,       "
        + "EOOR.COMPANY_NAME,       "
        + "EOOR.EOOR_PAYMENT_WAY,  "
        + "EOOR.EOOR_EXCEPT_ISSUE_TIME,        "
        + "EOOR.EOOR_EBLP_CODE,      "
        + "EOOR.EOOR_EBLP_NAME,     "
        + "EOOR.EOOR_SHIPPER_LONGITUDE,        "
        + "EOOR.EOOR_SHIPPER_LATITUDE,"
        + "EOOR.EOOR_CONSIGNEE_LONGITUDE,     "
        + "EOOR.EOOR_CONSIGNEE_LATITUDE,       "
        + "EOOR.EOOR_BOOK_ARRIVAL_TIME_TO,    "
        + "EOOR.EOOR_RESERVATION_ARRIVAL_TIME,"
        + "EOOR.EOOR_IS_WAVE_SYNC,  "
        + "EOOR.EOOR_EOSM_PM_CODE, "
        + "CDWH.IS_OUT_COLLAB_WH,    "
        + "CDWH.SERVICE_PROVIDERS,   "
        + "EOOR.EOOR_SPEC_CARRIER,  "
        + "EOOR.EOOR_IS_OUTSOURCE,  "
        + "ESUS.esus_login_name as creator_login_name,"
        + "ESUS.esus_user_name_cn as creator_name_cn,"
        + "eu1.esus_login_name as modifier_login_name, "
        + "eu1.esus_user_name_cn as modifier_name_cn "
        + "       FROM        "
        + "eo_c_order EOOR     "
        + "       LEFT JOIN    "
        + "ES_USER eu1        "
        + "    on EOOR.MODIFIER=eu1.esus_id        "
        + "       LEFT JOIN    "
        + "ES_USER ESUS      "
        + "    ON EOOR.CREATOR=ESUS.ESUS_ID   "
        + "       LEFT JOIN    "
        + "CD_WAREHOUSE CDWH        "
        + "    ON CDWH.WH_CODE=EOOR.EOOR_WAREHOUSER_CODE     "
        + "       JOIN "
        + "EB_CODE_MASTER EBCD      "
        + "    ON EOOR.Eoor_Order_Type_Code=EBCD.EBCD_CODE"
        + "    AND EBCD.EBCD_DICTIONARY_TYPE =?        "
        + "       WHERE       "
        + "1=1      "
        + "AND EOOR.REC_STATUS=0  --是否全冲  --预约状态      "
        + "AND EOOR.EOOR_CUSTOMER_ORDER_TIME >= ?+1/24/60    "
        + "AND EOOR.EOOR_CUSTOMER_ORDER_TIME< ?+1/24/60      "
        + "AND (    "
        + "    (    "
        + "        1=1"
        + "    )    "
        + ")        "
        + "       order by       "
        + "EOOR.MODIFY_TIME desc;";
    Pattern pattern = Pattern.compile("order\\s*by");
    String[] strs = pattern.split(sql);
    for (String string : strs) {
      System.out.println(string);
    }
  }
}
